### ISSUE TITLE
[Feature] Space characters in the url can be converted correctly.

### ISSUE THREAD

**Issue by LostJay** [lexiforest/curl_cffi#391] opened 2024-09-23 08:39 UTC
While requesting URLs with space characters, these characters are not coverted into '%20' properly( Or '+', which is often used as a short form of space in URL query strings), so an error which looks like 'curl: (3) URL rejected: Malformed input to a URL function' is most likely raised. I wonder if it could be more tolerant of URLs with unconverted space characters.

A similar prepare procedure is highly recommended before making a request just like the requests package. In requests, the method 'prepare_url' for class 'PreparedRequest' will handle this perfectly.

**Comment by lexiforest** [comment] 2024-09-23 08:57
Duplicate of #333

**Closed** 2024-09-24 01:38 UTC
Labels: enhancement
