### ISSUE TITLE
Unable to download libcurl-impersonate when installing package (build.py)

### ISSUE THREAD

**Issue by lrdcxdes** [lexiforest/curl_cffi#464] opened 2024-12-17 12:10 UTC
Please check the following items before reporting a bug, otherwise it may be closed immediately.

- [ + ] **This is NOT a site-related "bugs"**, e.g. some site blocks me when using curl_cffi,
    UNLESS it has been verified that the reason is missing pieces in the impersonation.
- [ + ] A code snippet that can reproduce this bug is provided, even if it's a one-liner.
- [ + ] Version information will be pasted as below.

**Describe the bug**
i think there is no valid archive in [lexiforest/curl-impersonate](https://github.com/lexiforest/curl-impersonate/releases/download/v0.8.2/libcurl-impersonate-v0.8.2.)

https://github.com/lexiforest/curl_cffi/blob/main/scripts/build.py#L114

**To Reproduce**
```bash
pip install --pre curl-cffi
```

**Expected behavior**

**Versions**
 - OS: Windows 10 Lite
 - curl_cffi version 0.8.0b7

**Additional context**
```log
Using ./lib64 to store libcurl-impersonate
      Downloading libcurl-impersonate-chrome from https://github.com/lexiforest/curl-impersonate/releases/download/v0.8.2/libcurl-impersonate-v0.8.2.x86_64-win32.tar.gz...
      Traceback (most recent call last):
        File "C:\Users\lord\PycharmProjects\dtekbot\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>    
          main()
        File "C:\Users\lord\PycharmProjects\dtekbot\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main        
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lord\PycharmProjects\dtekbot\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires   
          self.run_setup()
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 16, in <module>
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 145, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\setuptools\dist.py", line 319, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 279, in __init__
          self.finalize_options()
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\setuptools\dist.py", line 677, in finalize_options
          ep(self)
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\setuptools\dist.py", line 697, in _finalize_setup_keywords    
          ep.load()(self, ep.name, value)
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 216, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "C:\Users\lord\AppData\Local\Temp\pip-build-env-nsfao6eq\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "scripts/build.py", line 114, in <module>
          download_libcurl()
        File "scripts/build.py", line 69, in download_libcurl
          urlretrieve(url, file)
        File "C:\Users\lord\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
          with contextlib.closing(urlopen(url, data)) as fp:
                                  ^^^^^^^^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "C:\Users\lord\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 404: Not Found
      [end of output]```

**Comment by lexiforest** [comment] 2024-12-17 12:42
Duplicate of #400, also see the [release notes](https://github.com/lexiforest/curl_cffi/releases/tag/v0.8.0b7).

**Closed by lexiforest** 2024-12-17 12:42 UTC
Labels: bug
