### ISSUE TITLE
ImportError: dlopen failed: library "libcurl-impersonate-chrome.so.4" not found On Termux

### ISSUE THREAD

**Issue by ylasgamers** [lexiforest/curl_cffi#453] opened 2024-12-02 21:51 UTC
ImportError: dlopen failed: library "libcurl-impersonate-chrome.so.4" not found: needed by /data/data/com.termux/files/usr/lib/python3.10/site-packages/curl_cffi/_wrapper.abi3.so in namespace (default)
![photo_2024-12-03_04-38-09](https://github.com/user-attachments/assets/a699f646-5697-4f38-89e4-078ab7a60c2d)

**Comment by lexiforest** [comment] 2024-12-03 03:03
Duplicate of #74, let's track the issue there.

**Closed by lexiforest** 2024-12-03 03:03 UTC
Labels: bug
