### ISSUE TITLE
[BUG] 0.7.2 does not honor content-type header in posts when data is bytes

### ISSUE THREAD

**Issue by mitchcapper** [lexiforest/curl_cffi#399] opened 2024-09-28 17:04 UTC
**Describe the bug**
@ASAD-BE18 figured out the bug was in curl_cffi with https://github.com/rebane2001/matterport-dl/issues/137#issuecomment-2380584220 .  Running it through a proxy it was clear making a request like:
`OUR_SESSION.request(url=url, method="POST", headers={"Content-Type": "application/json"}, data=bytes(post_json_str, "utf-8"))`
worked in 0.7.1 sending a proper content type header like:
`Content-Type: application/json`
but in 0.7.2 it results in:
`Content-Type: application/octet-stream`

Not sure if setting the json object would work (json=) instead of passing the string itself.  I am guessing this is due to us converting the data to the byte array but I would assume any default content-type should be overwritten by the headers param.

**To Reproduce**
```
from curl_cffi import requests
r = requests.post("https://my.matterport.com/api/mp/models/graph", data=bytes("test", "utf-8"), headers={"Content-Type": "application/json"})
```

**Expected behavior**
request honors content type and doesn't override

**Versions**
curl_cffi 0.7.2 problem 0.7.1 ok

Can almost guarantee is the problem  https://github.com/lexiforest/curl_cffi/issues/395  is having too

**Comment by lexiforest** [comment] 2024-10-04 15:12
Duplicate of #395.

**Closed by lexiforest** 2024-10-04 15:12 UTC
Labels: bug
